In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as plb
import scipy.signal as signal
import pandas as pd

In [35]:
# Abrir batimetría idw

# cargar batimetria de arcgis
# ---------------------------
delta = 0.00090000000000002
x = np.asarray([(-81.876108860436 + 360) + i*delta for i in range(415)])
y = np.asarray([12.37755125039 + i*delta for i in range(417)])
# z = np.flipud(np.genfromtxt(r"G:\My Drive\TDG_Paula\Batimetria\Bat_50m\idw_50m_int4.txt", skip_header=6))
z = np.flipud(np.genfromtxt(r"G:\My Drive\TDG_Paula\Batimetria\Bat_100m\idw_100m.txt", skip_header=6))
# z[z == -9999] = nan
# z[np.where(z<0)] = nan

In [36]:
z.shape, x.shape, y.shape

((417, 415), (415,), (417,))

In [37]:
X_re, Y_re = np.meshgrid(x,y)
Z_re = np.reshape(z,(len(x)*len(y)))
X_re= np.reshape(X_re,(len(x)*len(y)))
Y_re= np.reshape(Y_re,(len(x)*len(y)))

df_data = pd.DataFrame({'x': X_re, 'y': Y_re, 'z': Z_re})
path = r'G:\My Drive\TDG_Paula\Batimetria\Bat_100m'
name_file = 'Bat_SAI_100m.xyz'
# path = r'G:\My Drive\TDG_Paula\Batimetria\Bat_50m'
# name_file = 'Bat_SAI_50m.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [38]:
df_data

x          y         z
0       278.123891  12.377551  1384.546
1       278.124791  12.377551  1390.750
2       278.125691  12.377551  1401.488
3       278.126591  12.377551  1413.447
4       278.127491  12.377551  1423.793
...            ...        ...       ...
173050  278.492891  12.751951  1104.834
173051  278.493791  12.751951  1065.784
173052  278.494691  12.751951  1034.983
173053  278.495591  12.751951  1015.882
173054  278.496491  12.751951  1008.151

[173055 rows x 3 columns]

In [3]:
ruta = r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\BATIMETRIA\BAT_SAI_GENERAL_PA_JD_100m\BAT_SAI_GENERAL_100m.txt"
df_data = pd.read_csv(ruta,sep = ',', usecols=['x','y','z'])
# df_data.rename(columns={'Z_1':'z'}, inplace=True)

In [4]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\BATIMETRIA\BAT_SAI_GENERAL_PA_JD_100m"
name_file = 'Bat_SAI_MERGE_JD_PA_100m.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [4]:
z = df_data.z.values
x = df_data.x.values
y = df_data.y.values
print (z.shape,x.shape,y.shape)

(7742,) (7742,) (7742,)


In [5]:
df_data

x          y      z
0     421044.0  1397280.0  960.0
1     421144.0  1397280.0  960.0
2     421244.0  1397280.0  960.0
3     421344.0  1397280.0  960.0
4     421444.0  1397280.0  960.0
...        ...        ...    ...
7737  423544.0  1392380.0   -5.0
7738  425044.0  1392880.0   -5.0
7739  425044.0  1392980.0   -5.0
7740  425144.0  1392980.0   -5.0
7741  425144.0  1393080.0   -5.0

[7742 rows x 3 columns]

In [6]:
df_data.loc[(df_data['x']> 420000) & (df_data['z']> 0),'z']= 29

In [7]:
df_data.loc[(df_data['x'] <= 420000) & (df_data['z']> 0), 'z']= 26

In [8]:
df_data.loc[df_data['z'] <= 0, 'z']= np.nan

In [9]:
df_data['z'].unique()

array([nan, 26., 29.])

In [10]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\CODIGOS"
name_file = 'Map_Temp.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [13]:
df_data.loc[(df_data['x']> 420000) & (df_data['z']> 0),'z']= 0
df_data.loc[(df_data['x'] <= 420000) & (df_data['z']> 0), 'z']= 0
df_data['z'].unique()

array([nan,  0.])

In [14]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\CODIGOS"
name_file = 'Map_water_level.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [16]:
df_data.loc[(df_data['x']> 420000) & (df_data['z']>= 0),'z']= 36
df_data.loc[(df_data['x'] <= 420000) & (df_data['z']>= 0), 'z']= 36
df_data['z'].unique()

array([nan, 36.])

In [17]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\CODIGOS"
name_file = 'Map_salt.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")