In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as plb
import scipy.signal as signal
import pandas as pd

In [3]:
ruta = r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\BATIMETRIA\BAT_SAI_GENERAL_PA_JD_100m\BAT_SAI_GENERAL_100m.txt"
df_data = pd.read_csv(ruta,sep = ',', usecols=['x','y','z'])
# df_data.rename(columns={'Z_1':'z'}, inplace=True)

In [4]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\BATIMETRIA\BAT_SAI_GENERAL_PA_JD_100m"
name_file = 'Bat_SAI_MERGE_JD_PA_100m.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [4]:
z = df_data.z.values
x = df_data.x.values
y = df_data.y.values
print (z.shape,x.shape,y.shape)

(7742,) (7742,) (7742,)


In [5]:
df_data

x          y      z
0     421044.0  1397280.0  960.0
1     421144.0  1397280.0  960.0
2     421244.0  1397280.0  960.0
3     421344.0  1397280.0  960.0
4     421444.0  1397280.0  960.0
...        ...        ...    ...
7737  423544.0  1392380.0   -5.0
7738  425044.0  1392880.0   -5.0
7739  425044.0  1392980.0   -5.0
7740  425144.0  1392980.0   -5.0
7741  425144.0  1393080.0   -5.0

[7742 rows x 3 columns]

In [6]:
df_data.loc[(df_data['x']> 420000) & (df_data['z']> 0),'z']= 29

In [7]:
df_data.loc[(df_data['x'] <= 420000) & (df_data['z']> 0), 'z']= 26

In [8]:
df_data.loc[df_data['z'] <= 0, 'z']= np.nan

In [9]:
df_data['z'].unique()

array([nan, 26., 29.])

In [10]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\CODIGOS"
name_file = 'Map_Temp.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [13]:
df_data.loc[(df_data['x']> 420000) & (df_data['z']> 0),'z']= 0
df_data.loc[(df_data['x'] <= 420000) & (df_data['z']> 0), 'z']= 0
df_data['z'].unique()

array([nan,  0.])

In [14]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\CODIGOS"
name_file = 'Map_water_level.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")

In [16]:
df_data.loc[(df_data['x']> 420000) & (df_data['z']>= 0),'z']= 36
df_data.loc[(df_data['x'] <= 420000) & (df_data['z']>= 0), 'z']= 36
df_data['z'].unique()

array([nan, 36.])

In [17]:
path =  r"G:\My Drive\TESIS_MAESTRIA_PAULAE\MODELO_NUMERICO\CODIGOS"
name_file = 'Map_salt.xyz'
np.savetxt(path+'/'+name_file, df_data.values, delimiter=' ', fmt = "%1.7f")